-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "arrivalTime" SET DATA TYPE TEXT,
ALTER COLUMN "departureTime" SET DATA TYPE TEXT;
